// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class PrihlasenieSaNespravneHesloTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void prihlaseniesanespravneheslo() {
    String email = "mizukage295@gmail.com";
    String nespravneHeslo = "sdsdsd";
    driver.get("https://www.martinus.sk/");
    driver.manage().window().maximize();
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    wait.until(ExpectedConditions.elementToBeClickable(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll"))).click();
    driver.findElement(By.cssSelector(".header-user__name")).click();
    driver.findElement(By.id("email")).sendKeys(email);
    driver.findElement(By.id("email")).sendKeys(Keys.ENTER);
    WebElement hesloElement = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("heslo")));
    driver.findElement(By.id("heslo")).sendKeys(nespravneHeslo);
    driver.findElement(By.id("heslo")).sendKeys(Keys.ENTER);
    assertThat(driver.findElement(By.cssSelector(".alert__content > strong")).getText(), is("Och, čosi nedobre :("));
    driver.quit();
  }
}
