// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;

public class PrihlasenieSaNespravneZadanyEmailTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void prihlaseniesanespravnezadanyemail() {
    String nespravnyEmail = "mizukage295gmail.com";
    driver.get("https://www.martinus.sk/");
    driver.manage().window().maximize();
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    wait.until(ExpectedConditions.elementToBeClickable(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll"))).click();
    driver.findElement(By.cssSelector(".header-user__name")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".header-user__name"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("email")).sendKeys(nespravnyEmail);
    driver.findElement(By.id("email")).sendKeys(Keys.ENTER);
    js.executeScript("window.scrollTo(0,0)");
    WebElement formTextElement = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".form-text")));
    assertThat(formTextElement.getText(), is("Je toto e-mail? Skontrolujte, prosím, či ste zadali správne vašu e-mailovú adresu."));
    driver.quit();
  }
}

