// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.containsString;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;

public class VyhladanieProduktuPodlaNazvuTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void vyhladanieproduktupodlanazvu() {
    String nazovProduktu = "frieren 1";
    ArrayList<String> coMaNazovObsahovat = new ArrayList<>();
    coMaNazovObsahovat.add("Frieren");
    coMaNazovObsahovat.add("1");

    driver.get("https://www.martinus.sk/");
    driver.manage().window().maximize();
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    wait.until(ExpectedConditions.elementToBeClickable(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll"))).click();
    driver.findElement(By.id("search-in-header")).click();
    driver.findElement(By.id("search-in-header")).sendKeys(nazovProduktu);
    driver.findElement(By.id("search-in-header")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".listing__item:nth-child(1) .listing__item__title > .link")).click();
    for (String text: coMaNazovObsahovat) {
      assertThat(driver.getTitle(), containsString(text));
    }
    driver.quit();
  }
}
