// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class VyhladanieKvizuTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void vyhladaniekvizu() {
    String kvizName = "Ako dobre poznáte Pýchu a predsudok?";
    driver.get("https://www.martinus.sk/");
    driver.manage().window().maximize();
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    wait.until(ExpectedConditions.elementToBeClickable(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll"))).click();
    driver.findElement(By.linkText("Knižný blog")).click();
    driver.findElement(By.linkText("Kvízy")).click();
    driver.findElement(By.id("search-in-header")).click();
    driver.findElement(By.id("search-in-header")).sendKeys(kvizName);
    driver.findElement(By.id("search-in-header")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText(kvizName)).click();
    assertThat(driver.findElement(By.cssSelector(".h1")).getText(), is(kvizName));
  }
}
